### ISSUE TITLE
Is the client secret has to be required in the invalidateToken operation (volos-oauth)?

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#63]
I'm using the password flow in order to generate tokens (with the connect middle-wares) and login users to my web app. This flow [doesn't require the client secret](https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L126). In order to logout users I want to do the same only with the invalidate middleware, but the [invalidateToken requires the client secret](https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L259).

Is the client secret has to be required in the invalidateToken operation ? Its not something that should be exposed in the client side.

Thanks,
Boris

**Comment by theganyo** [comment]
As in issue #44, we have to assume that invalidation will be done by a confidential client of the system. That said, I believe both these issues *could* be handled by you in your server app - assuming you have otherwise verified the legitimacy of your web or mobile client. 

Specifically, I have included the ability for you to override the endpoint controllers in your a127 app. You may put a controller with the name "volos-oauth.js" in your application. It will look something like this: https://github.com/apigee-127/volos/blob/master/swagger/lib/controllers/volos-oauth.js. You may override only the methods that you need. For example: https://github.com/apigee-127/volos/blob/master/swagger/test/support/controllers/volos-oauth.js.

Doing this will allow you to implement whatever you wish for those OAuth endpoints - including adding client_id and client_secret to the request before it is passed to the middleware - or even make completely different calls directly into the Volos OAuth module (or otherwise) to do your verification. I would just urge extreme caution about what you do in these controllers!

Will that address your needs?

Scott

**Comment by borisirota** [comment]
This will be a solution for this use case :)

Meanwhile, I came to the conclusion that the use of volos-oauth is an overkill for my needs and might not be the right tool for the moment. I only need to authenticate a web app users, not the whole oauth2 framework capabilities, which can be achieved by JWT (or maybe a simple redis token store customized to my needs). This will give me the flexibility to solve some issues we talked about in other issues I posted without the need of abusing a library that meant for other use cases and without the need of making too many requests to a database :)

Still thinking about it. Thanks for the reply !

Boris

**Comment by theganyo** [comment]
Actually, if you are just doing password authentication anyway, you probably need not worry about exposing the client_secret to your clients. Turn on only the password grant type and you needn't worry about clients having the secret because they'd only be able to generate keys with username / password.

**Comment by borisirota** [comment]
Yes You are right.
