### ISSUE TITLE
Suggestion: Add a helper to determine the valid grant types

### ISSUE THREAD

**Issue by emcpadden** [apigee-127/volos#75]
I'm new to OAuth so I hope this make sense.  

SUGGESTION: Adding the ability to specify a helper function in an a127/swagger file to specify the valid grant types would give more flexibility when an API is accessed by apps that have different levels of trust.

BACKGROUND (TLDR ;):
The API's that we will be looking to implement will have several different types of consumers.  

One type of consumer might be 3rd party apps that will need to use the Authorize Code grant type because we don't completely trust the 3rd party app.

Another type of consumer might be a partners server that we would allow to use Client Credentials grant type because we have a partner relationship with them.

And, yet another type of consumer might be mobile apps that our company creates that we will need to use Password Grant type because the app is on the phone of the user we are authenticating and we trust our own apps not to store the password.

So ... an interesting enhancement might be to be able to have the option to specify a helper function in the a127/swagger file that can be used to determine which grant types are allowed for a given client_id.  Or, it could pass in a grant type and client_id and return true/false to say whether that grant type is allowed for that client_id.  Or,  maybe there is some other way to accomplish this.

I was thinking that having something like this would allow the ability to have an API that you could effectively control the allowed grant types depending on how much you trust the app instead of having to treat all apps equally.  

...Ed

**Comment by theganyo** [comment]
Hey Ed,

This seems reasonable on it's face, but what is the actual the effect of this? I would think that how one authenticates should be generally determined by what credentials one has. I mean, if you give someone a id and secret, why then prevent them from using those credentials to authenticate? Alternatively, in the case of a client that you don't trust, why would you give them those credentials instead of relying on the user to enter their password? Is it that you don't trust the developers to use the correct authentication for the client they are creating?

Also, authentication isn't authorization. If you don't trust the client, wouldn't that mean more than you'd want to adjust what they are authorized to do once they authenticate, rather than how they can use the credentials you gave them to authenticate?

Just trying to flesh out what you're attempting to do here...

Thanks,
Scott

**Comment by emcpadden** [comment]
Hi Scott,

Thanks for your thought provoking comments.  Being new to OAuth, my head definitely spins as I try to understand it and how it would apply to our APIs.  

In what I am reading, it seems that it is recommended that serious consideration be given to what grant types are allowed for different situations.  I have a feeling that the APIs that we are looking to implement could easily have different types of clients.  WIth that in mind, I would think that we might want to limit which grant types we allow based on the developer.

For instance, I have seen lots of recommendations that you not allow third party apps to use the password grant type because you can't be sure that they are not storing the password, whereas, for user convenience you might want your own apps to be able to use the password grant type because they are under your control to make sure they take care not to store the password.

This is from [http://apigee.com/docs/api-services/content/implementing-password-grant-type](http://apigee.com/docs/api-services/content/implementing-password-grant-type) 
>The resource owner password (or "password") grant type is mostly used in cases where the app is highly trusted.


I am also confused as to what aspects of oauth I should be configuring inside my swagger file.  It makes sense to me that I would configure the Security section an the Security Definition section in order to specify which paths need to be secured and what the scopes are, etc.  

I guess I would need to configure the oauth service in the x-a127-services section so that volos would know how to verify the access token along with scopes.

Also, I am assuming the validGrantTypes and tokenPaths would be used when using the RemoteProxy.

In starting to think about how we might do oauth, as part of our multi tenant  system, I think we are going to need to become part of the process to generate the access token so that we can include some custom attributes.

For this, I would think that we would have some other oauth API in our organization that would have the tokenPaths needed.  Am I thinking correctly about this?

 
I do have a some other questions regarding the a127/volos/oauth/swagger questions but I am having trouble thinking about how to ask them with my very limited understanding.  When the cloud in my brain starts to clear, I put them up on the community forum :)

Thanks Scott for all the help you have given me and I apologize ahead of time for my ignorance on all of this.  Hopefully, the fog will lift soon :)

...Ed

**Comment by theganyo** [comment]
Hey Ed,

You are correct, the method of authentication is definitely dependent on the client. I don't really know your specific situation and how you're offering services, but I'll just throw out this in case it helps:

OAuth 2.0 specifically makes a distinction between "public" (cannot keep a secret) and "confidential" (can keep a secret) clients. This is within the client configuration itself. Certainly, if you embed a password (or client secret) in the client, you'd better trust it fully. There is also the potential that app requires a user login that your server maintains. For that, you could use either an indirect flow (auth code, implicit) or password. In the indirect flow, the user doesn't share their password with the app, so they don't need to trust it or the resource server too much. In the case of using the password, they need to trust the app & resource server not to do nefarious things with their password. But if the password is tied to the app and it's resource server anyway, that won't really matter.

As for what to configure in your swagger... yes, you would [configure](https://github.com/apigee-127/a127-documentation/wiki/Quick-Start:-Add-Apigee-OAuth#adding-oauth-20-security-to-the-api) both the Security Definition and Volos OAuth definition. And yes, you would configure validGrantTypes and tokenPaths on your Volos OAuth definition.

Also, you can override the controllers for your OAuth paths in a127.  If you take a look [here](https://github.com/apigee-127/volos/blob/master/swagger/lib/controllers/volos-oauth.js) you can see how the Volos Oauth Controller is implemented. It is designed so that you can override one or more of the functions if you wish. An example of overriding a single function is [here](https://github.com/apigee-127/volos/blob/master/swagger/test/support/controllers/volos-oauth.js). Perhaps this would help address your requirements?

Scott

**Comment by emcpadden** [comment]
Hi Scott,

> In the case of using the password, they need to trust the app & resource server not to do nefarious things with their password. 

I think what I am struggling with is how can I prevent some apps from even having the option of using the password grant type while allowing other apps (for instance the apps that our company produces) to be able to use the password grant type.  It seems like the way it is now, I'd have to let all apps be able to use password grant type if I wanted any to be able to use the password grant type.

> Also, you can override the controllers for your OAuth paths in a127.

OK, I think I understand.  I would set up the paths in the oauth path in the x-a127-services like this:
```
tokenPaths:  # These will be added to your paths section for you
        authorize: /authorize
        token: /accesstoken
        invalidate: /invalidate
        refresh: /refresh
```
Then in the paths section of the swagger doc, I could manually configure any of these paths (e.g. /accesstoken ) to override the controller and operation.  This way I could change or augment the standard volos methods. 

Do I have this right?  If this is what you mean, I should be able to do what I need to do.

I guess one misunderstanding I had was that I would have one oauth API that I would deploy or setup on ApigeeEdge that would handle the oauth for all of my APIs. Instead, I think what you are saying here is that each API would contain the paths for the oauth for that API.  Right?  

I guess with this, I would create a custom module with any special handling for creating the token and then use that same module in all of my APIs (since each API would handle its own oauth instead of having one separate oauth API).  Right? ... or am I misunderstanding something.

As always, thanks so much for helping understand this.

...Ed

**Comment by theganyo** [comment]
Yes, you'd set up the paths in the x-a127-services... But you won't declare the paths in the Swagger paths section, Volos will do this for you. You merely create a volos-oauth.js file (this specific file name) in your controllers directory and expose the functions relating to the paths you wish to override (note: the function names match the keys - not the path values). Once you do this, you can do whatever you'd like. Eg. you could address your desire to force certain clients to use specific grant types by just checking the client_id in your controller and send an error back if you won't allow it that particular grant for that client.

I don't want to prescribe how you must/should set up your system and I believe you should have the flexibility to create OAuth endpoints however you want. If you want a single set to service all APIs, you can do that. If you want multiple sets, you could do that as well. It really depends on what serves your purposes best. 

Scott

**Comment by emcpadden** [comment]
Perfect Scott!  This helps a lot.  

I guess one way I could do what I wanted as far as controlling which apps can use which grant types is to add all grant types I would want to support to the swagger file. 

Then use the technique that you describe above to override the calls to prevent apps from outside developers from getting access tokens for the password or client credential grant types.  

I think this would work ... right?

**Comment by theganyo** [comment]
Yes. Exactly. :)

**Comment by emcpadden** [comment]
Great! Thanks Scott ... I think the fog is slowly lifting :)  Thanks for all you help.

**Comment by theganyo** [comment]
You are certainly welcome!
